<?php
namespace Omnipay\Rede\Message;

use Omnipay\Rede\Message\AbstractRequest;
use Omnipay\Rede\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-11-07 at 18:47:09.
 */
class AbstractRequestTest extends TestCase
{

    /**
     * @var AbstractRequest
     */
    protected $object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object  = $this->createMock(AbstractRequest::class, [
            $this->getHttpClient(),
            $this->getHttpRequest(),
            'NTAwNzk1NTc6NDkxM2JiMjRhMDI4NDk1NGJlNzJjNDI1OGUyMjliODY=',//token de homologação do manual
            \Omnipay\Rede\Gateway::TEST_ENDPOINT
        ]);
    }


    public function testExtendsAbstractRequest()
    {
        return $this->assertInstanceOf(AbstractRequest::class, $this->object);
    }

}
