<?php
namespace Omnipay\Rede\Message;

use InvalidArgumentException;
use Omnipay\Common\CreditCard;
use Omnipay\Common\Exception\InvalidRequestException;
use Omnipay\Rede\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-11-07 at 19:08:31.
 */
class AuthorizationRequestTest extends TestCase
{

    /**
     * @var AuthorizationRequest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AuthorizationRequest(
            $this->getHttpClient(),
            $this->getHttpRequest(),
            'NTAwNzk1NTc6NDkxM2JiMjRhMDI4NDk1NGJlNzJjNDI1OGUyMjliODY=',//token de homologação do manual
            \Omnipay\Rede\Gateway::TEST_ENDPOINT
        );
    }

    public function testMustThrowWhenInstallmentValueIsNotAnInteger()
    {
        $this->expectException(InvalidArgumentException::class);
        $this->object->setInstallments('not an integer');
    }

    public function testMustThrowWhenInstallmentValueIsLessThanOne()
    {
        for ($i = 0; $i < -100; --$i) {
            $this->expectException(InvalidArgumentException::class);
            $this->object->setInstallments($i);
        }
    }

    public function testMustThrowWhenInstallmentValueIsBiggerThanTwelve()
    {
        for ($i = 12; $i <= 100; ++$i) {
            $this->expectException(InvalidArgumentException::class);
            $this->object->setInstallments($i);
        }
    }

    public function testMustThrowWhenRequestIsIncomplete()
    {
        $this->expectException(InvalidRequestException::class);
        $this->object->getData();
    }

    public function testHasCorrectData()
    {
        $this->populateObject();
        $keys = [
            'capture',
            'kind',
            'reference',
            'amount',
            'installments',
            'cardHolderName',
            'cardNumber',
            'expirationMonth',
            'expirationYear',
            'securityCode'
        ];
        $data = $this->object->getData();
        foreach ($keys as $k) {
            $this->assertArrayHasKey($k, $data);
        }
    }

    public function testMustThrowWhenKindIsInvalid()
    {
        $this->object->setKind('credit'); //OK
        $this->object->setKind('debit'); //OK
        $this->expectException(InvalidArgumentException::class);
        $this->object->setKind('other method'); //OK
    }

    public function testMustNotThrowWhenInstallmentValueIsValid()
    {
        for ($i = 1; $i <= 12; ++$i) {
            $this->object->setInstallments($i);
        }
    }

    public function testHasAuthorizationInDefaultHeader()
    {
        $this->assertArrayHasKey('Authorization', $this->object->getDefaultHeaders());
    }

    public function testDoNotCapture()
    {
        $this->populateObject();
        $data = $this->object->getData();
        $this->assertArrayHasKey('capture', $data);
        $this->assertFalse($data['capture']);
    }

    public function testSuccessfulTransaction()
    {
        $gateway = \Omnipay\Omnipay::getFactory()->create('Rede');
        $gateway->setTestMode(true);
        $defaultParameters = $gateway->getDefaultParameters();
        $gateway->setMerchantId($defaultParameters['merchantId']);
        $gateway->setMerchantKey($defaultParameters['merchantKey']);

        $this->object = $gateway->authorize();
        $this->populateValidObject();

        $response = $this->object->send();

        $this->assertTrue($response->isSuccessful());
    }

    public function testFailedTransaction()
    {
        $gateway = \Omnipay\Omnipay::getFactory()->create('Rede');
        $gateway->setTestMode(true);
        $defaultParameters = $gateway->getDefaultParameters();
        $gateway->setMerchantId($defaultParameters['merchantId']);
        $gateway->setMerchantKey($defaultParameters['merchantKey']);

        $this->object = $gateway->authorize();
        $this->populateObject();

        $response = $this->object->send();

        $this->assertFalse($response->isSuccessful());
    }

    private function populateObject()
    {
        $card = new CreditCard();
        $this->object->setTestMode(true);
        $this->object->setCard($card);
        $this->object->getCard()
            ->setName('Waldosn Patrício')
            ->setCvv(123)
            ->setNumber('4485787226954681')
            ->setExpiryYear(date('Y') + 1)
            ->setExpiryMonth(5);
        $this->object->setAmount(100.00);
        $this->object->setReference(uniqid());
    }

    private function populateValidObject()
    {
        $card = new CreditCard();
        $this->object->setTestMode(true);
        $this->object->setCard($card);
        $this->object->getCard()
            ->setName('Waldosn Patrício')
            ->setCvv(132)
            ->setNumber('5448280000000007')
            ->setExpiryYear(date('Y') + 1)
            ->setExpiryMonth(1);
        $this->object->setAmount(100.00);
        $this->object->setReference(uniqid());
    }

}
